"""OpenHull — agent-orchestrated parametric ship preliminary design.

From a task book (ship type, deadweight, service speed, trading range)
to principal dimensions, hydrostatics, a lines plan, performance
estimates, and drawing outputs — with every quantity validated against
published benchmark ships (see AGENTS.md for the binding conventions).
"""

from importlib.metadata import PackageNotFoundError, version

from .drawing import (
    draw_lines_plan,
    save_lines_plan_dxf,
    save_offsets_csv,
)
from .fairness import (
    FairnessIssue,
    FairnessReport,
    check_fairness,
)
from .geometry import (
    JBC_KM_TARGET_M,
    OffsetsTable,
    jbc_parent_offsets,
    load_offsets_csv,
    load_parent_offsets,
    scale_offsets,
)
from .linesplan import (
    LackenbyReport,
    TRANSFORM_ALGORITHMS,
    area_curve,
    lackenby_transform,
    parent_to_taskbook,
)
from .freeboard import (
    FreeboardResult,
    TABLE_3_9_BASIC_FREEBOARD,
    minimum_freeboard,
    tabular_basic_freeboard,
)
from .hydrostatics import (
    bonjean_areas,
    hydrostatics_at,
    hydrostatics_table,
    simpson,
    trapezoid,
    waterplane,
)
from .propulsion import (
    PropulsionFactors,
    SpeedSolution,
    propulsion_factors,
    solve_service_speed,
)
from .resistance import (
    AYRE_V_SQRT_L_MAX,
    AYRE_V_SQRT_L_MIN,
    AyreCorrection,
    AyreResult,
    RESISTANCE_ALGORITHMS,
    ResistanceAlgorithmInfo,
    ayre_effective_power,
    resistance_algorithms,
)
from .main_dimensions import (
    B_OVER_T_BAND,
    DEFAULT_ALGORITHM,
    MAIN_DIMENSION_ALGORITHMS,
    AlgorithmInfo,
    RatioParameters,
    estimate_main_dimensions,
    required_b_over_t_at_draft,
)
from .spec import (
    SEAWATER_DENSITY,
    Hydrostatics,
    HydrostaticsTable,
    ShipSpec,
    SpecValidationError,
    knots_to_ms,
    ms_to_knots,
)
from .stability import (
    BUOYANCY_TOLERANCE,
    GZ_MAX_ANGLE_DEG,
    GZ_VOLUME_TOLERANCE,
    LCG_TOLERANCE,
    FloatingPosition,
    GZCriterion,
    GZCurveResult,
    GZPoint,
    InitialStability,
    StabilityCriteriaResult,
    Tank,
    TrimStep,
    WEATHER_GUST_FACTOR,
    WEATHER_WIND_PRESSURE_PA,
    WeatherCriterionResult,
    floating_position,
    free_surface_arm,
    free_surface_correction,
    gz_curve,
    initial_stability,
    intact_stability_criteria,
    weather_criterion,
)
from .weight_balance import (
    BULK_CARRIER_STEEL_EXPONENTS,
    DEFAULT_WEIGHT_ALGORITHM,
    WEIGHT_ALGORITHMS,
    BalanceStep,
    ComponentWeightParameters,
    LightweightBreakdown,
    WeightAlgorithmInfo,
    WeightBalanceResult,
    bulkcarrier_deadweight_ratio_statistics,
    outfit_area_coefficient_from_parent,
    solve_weight_balance,
    steel_cubic_coefficient_from_parent,
    steel_exponent_coefficient_from_parent,
)

try:
    __version__ = version("openhull")
except PackageNotFoundError:  # running from a source tree without install
    __version__ = "0.0.0.dev0"

__all__ = [
    "__version__",
    "SEAWATER_DENSITY",
    "DEFAULT_ALGORITHM",
    "MAIN_DIMENSION_ALGORITHMS",
    "AlgorithmInfo",
    "B_OVER_T_BAND",
    "required_b_over_t_at_draft",
    "AYRE_V_SQRT_L_MAX",
    "AYRE_V_SQRT_L_MIN",
    "AyreCorrection",
    "AyreResult",
    "RESISTANCE_ALGORITHMS",
    "ResistanceAlgorithmInfo",
    "PropulsionFactors",
    "SpeedSolution",
    "DEFAULT_WEIGHT_ALGORITHM",
    "WEIGHT_ALGORITHMS",
    "BalanceStep",
    "ComponentWeightParameters",
    "Hydrostatics",
    "HydrostaticsTable",
    "LightweightBreakdown",
    "RatioParameters",
    "ShipSpec",
    "SpecValidationError",
    "WeightAlgorithmInfo",
    "WeightBalanceResult",
    "BULK_CARRIER_STEEL_EXPONENTS",
    "BUOYANCY_TOLERANCE",
    "JBC_KM_TARGET_M",
    "FloatingPosition",
    "FreeboardResult",
    "FairnessIssue",
    "FairnessReport",
    "GZCriterion",
    "GZCurveResult",
    "GZPoint",
    "GZ_MAX_ANGLE_DEG",
    "GZ_VOLUME_TOLERANCE",
    "InitialStability",
    "LCG_TOLERANCE",
    "LackenbyReport",
    "OffsetsTable",
    "StabilityCriteriaResult",
    "TABLE_3_9_BASIC_FREEBOARD",
    "Tank",
    "TRANSFORM_ALGORITHMS",
    "TrimStep",
    "WEATHER_GUST_FACTOR",
    "WEATHER_WIND_PRESSURE_PA",
    "WeatherCriterionResult",
    "bulkcarrier_deadweight_ratio_statistics",
    "bonjean_areas",
    "estimate_main_dimensions",
    "ayre_effective_power",
    "check_fairness",
    "propulsion_factors",
    "solve_service_speed",
    "floating_position",
    "free_surface_correction",
    "free_surface_arm",
    "gz_curve",
    "intact_stability_criteria",
    "weather_criterion",
    "hydrostatics_at",
    "hydrostatics_table",
    "initial_stability",
    "jbc_parent_offsets",
    "knots_to_ms",
    "lackenby_transform",
    "load_parent_offsets",
    "parent_to_taskbook",
    "scale_offsets",
    "area_curve",
    "draw_lines_plan",
    "load_offsets_csv",
    "minimum_freeboard",
    "ms_to_knots",
    "outfit_area_coefficient_from_parent",
    "resistance_algorithms",
    "save_lines_plan_dxf",
    "save_offsets_csv",
    "simpson",
    "solve_weight_balance",
    "steel_cubic_coefficient_from_parent",
    "steel_exponent_coefficient_from_parent",
    "tabular_basic_freeboard",
    "trapezoid",
    "waterplane",
]
